### ISSUE TITLE
What to do with memeseeks

### ISSUE THREAD

**Issue by ihategithubbb** [BigSlice/-tg-station#41]
So are we gonna replace them or just remove them entirely?
If we're gonna replace them, we could perhaps use this sprite here(stolen from a thread of /tg/):
http://i.imgur.com/YFTBOct.png
Give it a few tools and a law not to harm and we're ready to go.
Although we could make something humanoid for more complicated tasks(or perhaps give those guys a single hand like MoMMIs?)
Color scheme looks a big too bright, we could change it too, also I say that as time passes, they take damage but become slightly faster, up until they dissapear when reaching a time limit(no fucking "hurr must kill master" bullshit)
EDIT: Best part about that sprite is that it kinda fits with the current memeseek box too
EDIT²:If we want humanoids, /tg/ has some nice sprites for we to "borrow" too.
http://i.imgur.com/dacpqQF.png

**Comment by BigSlice** [comment]
For now, it's a complete removal. Golems achieve the same purpose, and the players seem to hate them. Until public opinion changes, this will remain the case.

**Comment by ifuckinghategithub** [comment]
Most people seemed to advocate for a repurposal rather than a complete removal actually, not to mention that golems fill in an entirely different niche due to being permanent and being slow as fuck and thus unable to complete any tasks in a timely manner.
In any case, there should be a poll at the very least, removing content entirely is /tg/ tier shit.
